install.packages(c("parallel", "foreach", "vegan", "stringdist", "doParallel", "tidyverse", "gtools", "dplyr"))
install.packages("Rcpp")
install.packages("RcppArmadillo")
install.packages('gsubfn')
install.packages('zoo')
install.packages('plyr')
install.packages('ggsci')
install.packages('igraph')
install.packages('tidygraph')
install.packages('RColorBrewer')
install.packages("purrr")
install.packages("plot3D")
install.packages("./rELA.v0.51.tar.gz")

#install.packages("/aptmp/htoju/NARO3000_ELA_051/rELA.v0.51.tar.gz")
